<a href="https://colab.research.google.com/github/sigvehaug/CAS-Applied-Data-Science/blob/master/Module-1/M1-D1-DM-Sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook 1, Module 1, Data and Data Management, CAS Applied Data Science, 2023-08-23, S. Haug, University of Bern.

Prerequisite for this notebook is some basic Python experience.

Please also look at the first batch of [these slides](https://docs.google.com/presentation/d/1BrlQQGDnEpr8lBiEd9uO-Kw2-WOInAEP-cv-xdUwB4Y/edit?usp=sharing) before doing this notebook. They offer an introduction to data.

ChatGPT is able to write most of the code needed for this notebook. Please use it if you like !

# 1. Data Management

Estimated study time is about 2 hours. According to your background and how much you want to learn, you may need more or less. You are supposed to google, read manuals and chat with others during working through this notebook in order to benefit fully.

**Learning outcomes - after completion you**
- Know about data sources, types and formats (see lecture slides via link above)
- Able to import and export data in Python
- Able to do simple things with dataframes in Python
- Know about data volumes, metadata and quality
- Able to plot histograms and scatter plots in Python (tomorrow)

**Documentation on Pandas DataFrame**
- Python: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

## Outline

     0. About data management
     1. Getting used to Jupyter notebooks / colab
     2. Import datasets into a Python dataframe
     3. Indexing on a dataframe
     4. Sorting
     5. Filtering
     6. Exporting
     7. Missing and bad data
     8. Metadata
     9. Working on the filesystem

### 0. About data management

Handling or managing data involves many steps and technologies at many levels. Data may be colleccted by sensors. It can be a camera, a temperature sensor, a telescope, a microscope (with a camera), a microphone, a particle detector etc. Normally the data is then digitised, maybe preprocessed and written to some media in a certain format, e.g. as a comma separated value (csv) file to a hard disk. This part of the data management is normally taken care of by engineers.

Data may also be collected from all sorts of databases, so data already collected somehow. Time series of financial data, customers, passengers, facebook likes, twitter tweets etc. This is data which is normally already on a media with some interface for access, e.g. paper to be read by a camera, a file on youtube, a table on wikipedia etc. We will look at some ways to collect such data. Some programming and computer skills are needed to do so. It may be that this part of the data management is taken care of by specialised computer scientists, but it may also be expected from a data scientist to have these skills.

Analysing data with statisitical and machine learning tools, requires that the data is colleceted, cleaned and prepared for the tools. This is very often a very large part of a data analytics project and a prerequisite. It may involve removing bad data, filter out redundant and noisy data, unify the formats and types, transform the data etc.
Thus, a data scientist must be able to perform this part of the data management. This notebook shows the basic operations with Python pandas. With other tools the concepts and operations are very similar.

After the data analysis, after the extraction of information and the creation of knowledge, the data is often stored or archived for the future (if this seems cheaper than regenerating the data at a later point). In larger institutions this part of the data management may include educated librarians and others, not necessarily the data scientist.  

**In this notebook we only look at a few examples on how to do datamanagement with dataframes. Pandas are extremly powerful and we cannot show everything in a couple of hours. You will become more and more experienced when you work on your module projects. Probably whatever you want to do with your dataframe, there is a way to do it. If not, it probably doesn't make much sense what wou want to do.**

Any questions?

### 1. Getting used to Jupyter computational notebooks and Colab

With Jupyter you can write rich text notebooks with executable code via your browser. There are several so-called kernels or computational back ends, i.e Python, R, Julia, bash etc can be supported. The text is written as Markdown. Latex is also supported (good for math). You can export the notebook in various formats, e.g. html. Everything can be done via the various tabs, however, the key shortcuts make you faster.

*Useful key combinations*

- Shift Enter or Control Enter = Run cell
- Option/Alt Enter = Run cell and Insert new cell below

### Exercise 1 (10 min)
- Change and run this cell
- Add a new cell and execute some python statement in it
- Study the tabs in the menu of your jupyter (lab) notebook

In [1]:
# Write some more Python code here

print('Hello CAS')
for i in range(10):
  print('I am counting %1d' % (i))

Hello CAS
I am counting 0
I am counting 1
I am counting 2
I am counting 3
I am counting 4
I am counting 5
I am counting 6
I am counting 7
I am counting 8
I am counting 9

### 2. Import a dataset into a Pandas DataFrame

Pandas is a Python Module for data analysis and manipulation and management. It has the data structure DataFrame which is quite powerful. Features

- DataFrame object for data management with integrated indexing.
- Tools for reading and writing data between in-memory data structures and different file formats.
- Data alignment and integrated handling of missing data.
- Reshaping and pivoting of data sets.
- Label-based slicing, fancy indexing, and subsetting of large data sets.
- Data structure column insertion and deletion.
- Group by engine allowing split-apply-combine operations on data sets.
- Data set merging and joining.
- Hierarchical axis indexing to work with high-dimensional data in a lower-dimensional data structure.
- Time series-functionality: Date range generation and frequency conversion, moving window statistics, moving window linear regressions, date shifting and lagging.

The module is highly optimized for performance, with critical code parts written in Cython or C. Documentation here: https://pandas.pydata.org/pandas-docs/stable/api.html

For input/output (I/O) there are methods for reading EXCEL, SQL databases, HTML tables, clipboard, SAS, STATA etc.

In [15]:
# Upload the local data file to colab
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv

In [9]:
# import the python module pandas with the abbreviation pd
import pandas as pd
# Read the data in the iris.csv file into a dataframe
# If you work on colab, you need the data file on colab of course
dataframe = pd.read_csv('Iris.csv',dtype='str',header=0,names=['slength','swidth','plength','pwidth','species']) # data type is a string (str), i.e. not converted into numbers
dataframe # print data

FileNotFoundError: [Errno 2] No such file or directory: 'Iris.csv'

The dataframe method shows 50 rows per default. We can change this as we like:

In [18]:
pd.set_option('display.max_rows', None)

In [19]:
dataframe[0:20]

   slength swidth plength pwidth      species
1      5.1    3.5     1.4    0.2  Iris-setosa
2      4.9    3.0     1.4    0.2  Iris-setosa
3      4.7    3.2     1.3    0.2  Iris-setosa
4      4.6    3.1     1.5    0.2  Iris-setosa
5      5.0    3.6     1.4    0.2  Iris-setosa
6      5.4    3.9     1.7    0.4  Iris-setosa
7      4.6    3.4     1.4    0.3  Iris-setosa
8      5.0    3.4     1.5    0.2  Iris-setosa
9      4.4    2.9     1.4    0.2  Iris-setosa
10     4.9    3.1     1.5    0.1  Iris-setosa
11     5.4    3.7     1.5    0.2  Iris-setosa
12     4.8    3.4     1.6    0.2  Iris-setosa
13     4.8    3.0     1.4    0.1  Iris-setosa
14     4.3    3.0     1.1    0.1  Iris-setosa
15     5.8    4.0     1.2    0.2  Iris-setosa
16     5.7    4.4     1.5    0.4  Iris-setosa
17     5.4    3.9     1.3    0.4  Iris-setosa
18     5.1    3.5     1.4    0.3  Iris-setosa
19     5.7    3.8     1.7    0.3  Iris-setosa
20     5.1    3.8     1.5    0.3  Iris-setosa

In [20]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   slength  150 non-null    object
 1   swidth   150 non-null    object
 2   plength  150 non-null    object
 3   pwidth   150 non-null    object
 4   species  150 non-null    object
dtypes: object(5)
memory usage: 7.0+ KB

Find out on wikipedia what this Iris data is about.

### Hint

There are some ways to get help about modules and methods in Jupyter:

In [21]:
dataframe. #(hover over the object to see its methods)

SyntaxError: ignored

Get help about this object, if there is any:

In [ ]:
dataframe?

And, what you will probably use the most, the online package information and examples by googling or ChatGPT.

### Exercise 2 (10 min)

Read the Swiss BAG Corona data on deaths into a dataframe and look at it. The URL is
https://www.covid19.admin.ch/api/data/20230815-7ixiby4u/sources/COVID19Death_geoRegion_sex_w.csv

There are also json files on that server. If you want to use them instead, consult https://pandas.pydata.org/docs/reference/io.html in order to find out how to read a json file into a pandas dataframe.

In [11]:
# Write your code here
pd.set_option('display.max_rows',20)
url = 'C:/Users/tim94/OneDrive/Dokumente/Universität Bern/Data Acquisition and Management/data/COVID19Death_geoRegion.csv'
df = pd.read_csv(url)
df.tail()

,geoRegion,datum,entries,sumTotal,timeframe_14d,timeframe_all,offset_last7d,sumTotal_last7d,offset_last14d,sumTotal_last14d,...,inzsum14d,sumdelta7d,inzdelta7d,type,type_variant,version,datum_unit,entries_letzter_stand,entries_neu_gemeldet,entries_diff_last
30242,ZH,2022-12-28,0,1876,False,True,1884,0,1880,0,...,0.26,0.0,0.00,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,2
30243,ZH,2022-12-29,0,1876,False,True,1884,0,1880,0,...,0.19,-1.0,-0.06,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,2
30244,ZH,2022-12-30,1,1877,False,True,1884,0,1880,0,...,0.26,1.0,0.06,COVID19Death,NaN,2023-01-24_06-03-16,day,1,0,2
30245,ZH,2022-12-31,0,1877,False,True,1884,0,1880,0,...,0.26,-1.0,-0.06,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,2
30246,ZH,2023-01-01,0,1877,False,True,1884,0,1880,0,...,0.26,0.0,0.00,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,2

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30247 entries, 0 to 30246
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   geoRegion              30247 non-null  object
 1   datum                  30247 non-null  object
 2   entries                30247 non-null  int64
 3   sumTotal               30247 non-null  int64
 4   timeframe_14d          30247 non-null  bool
 5   timeframe_all          30247 non-null  bool
 6   offset_last7d          30247 non-null  int64
 7   sumTotal_last7d        30247 non-null  int64
 8   offset_last14d         30247 non-null  int64
 9   sumTotal_last14d       30247 non-null  int64
 10  offset_last28d         30247 non-null  int64
 11  sumTotal_last28d       30247 non-null  int64
 12  sum7d                  30073 non-null  float64
 13  sum14d                 29870 non-null  float64
 14  mean7d                 30160 non-null  float64
 15  mean14d                30073 non-null  float64
 16  entries_diff_last_age  30247 non-null  int64
 17  pop                    30247 non-null  int64
 18  inz_entries            30247 non-null  float64
 19  inzsumTotal            30247 non-null  float64
 20  inzmean7d              30160 non-null  float64
 21  inzmean14d             30073 non-null  float64
 22  inzsumTotal_last7d     0 non-null      float64
 23  inzsumTotal_last14d    0 non-null      float64
 24  inzsumTotal_last28d    174 non-null    float64
 25  inzsum7d               30073 non-null  float64
 26  inzsum14d              29870 non-null  float64
 27  sumdelta7d             30044 non-null  float64
 28  inzdelta7d             30044 non-null  float64
 29  type                   30247 non-null  object
 30  type_variant           0 non-null      float64
 31  version                30247 non-null  object
 32  datum_unit             30247 non-null  object
 33  entries_letzter_stand  30247 non-null  int64
 34  entries_neu_gemeldet   30247 non-null  int64
 35  entries_diff_last      30247 non-null  int64
dtypes: bool(2), float64(16), int64(13), object(5)
memory usage: 7.9+ MB

### 3. Indexing on a DataFrame

By methods (we are back to our clean and simple Iris dataset):

In [21]:
df.iat[149,0] # access single cell by integer numbers (row 149, column 0 / first column), faster that loc and iloc

'CH'

In [20]:
df.iat[1,1]=10 # Assign a new value
df.head()
df[0:3]

,geoRegion,datum,entries,sumTotal,timeframe_14d,timeframe_all,offset_last7d,sumTotal_last7d,offset_last14d,sumTotal_last14d,...,inzsum14d,sumdelta7d,inzdelta7d,type,type_variant,version,datum_unit,entries_letzter_stand,entries_neu_gemeldet,entries_diff_last
0,CH,2020-02-24,0,0,False,True,13912,0,13903,0,...,NaN,NaN,NaN,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,10
1,CH,10,0,0,False,True,13912,0,13903,0,...,NaN,NaN,NaN,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,10
2,CH,2020-02-26,0,0,False,True,13912,0,13903,0,...,NaN,NaN,NaN,COVID19Death,NaN,2023-01-24_06-03-16,day,0,0,10

Indexing a group/subset of the dataframe by loc (column names) or iloc (index)

In [27]:
sdf = df.iloc[0:10,0:5]
sdf
df.loc[2]
df.iloc[1,0:10]

geoRegion              CH
datum                  10
entries                 0
sumTotal                0
timeframe_14d       False
timeframe_all        True
offset_last7d       13912
sumTotal_last7d         0
offset_last14d      13903
sumTotal_last14d        0
Name: 1, dtype: object

**Important**
When you assign a (subset) of dataframe to a new one like above, no copy is made. This means that if you change values of the new frame, also the orginal frame will be changed. If you want a copy, you need to use the copy method.

Indexing by column names...

In [29]:
sdf['slength']

1     5.1
2     4.9
3     4.7
4     4.6
5     5.0
6     5.4
7     4.6
8     5.0
9     4.4
10    4.9
Name: slength, dtype: object

Selecting (filtering) by column valuess_df = dataframe[dataframe['species']=='Iris-setosa']

In [30]:
s_df = dataframe[dataframe['species']=='Iris-virginica']

In [31]:
s_df

    slength swidth plength pwidth         species
101     6.3    3.3     6.0    2.5  Iris-virginica
102     5.8    2.7     5.1    1.9  Iris-virginica
103     7.1    3.0     5.9    2.1  Iris-virginica
104     6.3    2.9     5.6    1.8  Iris-virginica
105     6.5    3.0     5.8    2.2  Iris-virginica
..      ...    ...     ...    ...             ...
146     6.7    3.0     5.2    2.3  Iris-virginica
147     6.3    2.5     5.0    1.9  Iris-virginica
148     6.5    3.0     5.2    2.0  Iris-virginica
149     6.2    3.4     5.4    2.3  Iris-virginica
150     5.9    3.0     5.1    1.8  Iris-virginica

[50 rows x 5 columns]

Vectorized dataframe manipulations...

In [32]:
sdf['half slength']=sdf['slength'].astype('float')/2.
sdf

   slength swidth plength pwidth      species  half slength
1      5.1    3.5     1.4    0.2  Iris-setosa          2.55
2      4.9     10     1.4    0.2  Iris-setosa          2.45
3      4.7    3.2     1.3    0.2  Iris-setosa          2.35
4      4.6    3.1     1.5    0.2  Iris-setosa          2.30
5      5.0    3.6     1.4    0.2  Iris-setosa          2.50
6      5.4    3.9     1.7    0.4  Iris-setosa          2.70
7      4.6    3.4     1.4    0.3  Iris-setosa          2.30
8      5.0    3.4     1.5    0.2  Iris-setosa          2.50
9      4.4    2.9     1.4    0.2  Iris-setosa          2.20
10     4.9    3.1     1.5    0.1  Iris-setosa          2.45

Grouping ...

In [33]:
gdf=dataframe.groupby('species')
print(gdf.ngroups)
print(gdf.size())
gdf_virginica = gdf.get_group('Iris-virginica')
gdf_virginica.head()

3
species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

    slength swidth plength pwidth         species
101     6.3    3.3     6.0    2.5  Iris-virginica
102     5.8    2.7     5.1    1.9  Iris-virginica
103     7.1    3.0     5.9    2.1  Iris-virginica
104     6.3    2.9     5.6    1.8  Iris-virginica
105     6.5    3.0     5.8    2.2  Iris-virginica

### 4. Sorting on a DataFrame

...

In [34]:
#adf = pd.read_csv('iris.csv',names=['slength','swidth','plength','pwidth','species'])
dataframe

    slength swidth plength pwidth         species
1       5.1    3.5     1.4    0.2     Iris-setosa
2       4.9     10     1.4    0.2     Iris-setosa
3       4.7    3.2     1.3    0.2     Iris-setosa
4       4.6    3.1     1.5    0.2     Iris-setosa
5       5.0    3.6     1.4    0.2     Iris-setosa
..      ...    ...     ...    ...             ...
146     6.7    3.0     5.2    2.3  Iris-virginica
147     6.3    2.5     5.0    1.9  Iris-virginica
148     6.5    3.0     5.2    2.0  Iris-virginica
149     6.2    3.4     5.4    2.3  Iris-virginica
150     5.9    3.0     5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [35]:
dataframe.sort_values(['slength','swidth'])
#dataframe.sort_values(['slength'])

    slength swidth plength pwidth         species
14      4.3    3.0     1.1    0.1     Iris-setosa
9       4.4    2.9     1.4    0.2     Iris-setosa
39      4.4    3.0     1.3    0.2     Iris-setosa
43      4.4    3.2     1.3    0.2     Iris-setosa
42      4.5    2.3     1.3    0.3     Iris-setosa
..      ...    ...     ...    ...             ...
119     7.7    2.6     6.9    2.3  Iris-virginica
123     7.7    2.8     6.7    2.0  Iris-virginica
136     7.7    3.0     6.1    2.3  Iris-virginica
118     7.7    3.8     6.7    2.2  Iris-virginica
132     7.9    3.8     6.4    2.0  Iris-virginica

[150 rows x 5 columns]

You may measure the time needed for the execution, e.g. with the operating system command "time". System commands are executed with a %:

In [36]:
%time dataframe[dataframe['species']=='Iris-setosa'].sort_values('slength')

CPU times: user 1.63 ms, sys: 0 ns, total: 1.63 ms
Wall time: 1.67 ms

   slength swidth plength pwidth      species
14     4.3    3.0     1.1    0.1  Iris-setosa
9      4.4    2.9     1.4    0.2  Iris-setosa
39     4.4    3.0     1.3    0.2  Iris-setosa
43     4.4    3.2     1.3    0.2  Iris-setosa
42     4.5    2.3     1.3    0.3  Iris-setosa
..     ...    ...     ...    ...          ...
37     5.5    3.5     1.3    0.2  Iris-setosa
34     5.5    4.2     1.4    0.2  Iris-setosa
19     5.7    3.8     1.7    0.3  Iris-setosa
16     5.7    4.4     1.5    0.4  Iris-setosa
15     5.8    4.0     1.2    0.2  Iris-setosa

[50 rows x 5 columns]

In [37]:
%ls -l # list the file in your current directory with the linux command ls

total 12
-rw-r--r-- 1 root root 5107 Aug 22 08:43 Iris.csv
drwxr-xr-x 1 root root 4096 Aug 18 13:32 sample_data/

Here is a cheat sheet for common linux commands: https://files.fosswire.com/2007/08/fwunixref.pdf

### 5. Filtering on a DataFrame
...

In [38]:
# Create a dataframe with a one column telling if slength is larger than 5.0
dataframe['slength'].astype('float')>5.0 # Returns a vector with booleans

1       True
2      False
3      False
4      False
5      False
       ...
146     True
147     True
148     True
149     True
150     True
Name: slength, Length: 150, dtype: bool

In [39]:
# We can apply the filtering result to a new dataframe
df_large = dataframe[dataframe['slength'].astype('float')>5.0]

In [40]:
# And print it
df_large

    slength swidth plength pwidth         species
1       5.1    3.5     1.4    0.2     Iris-setosa
6       5.4    3.9     1.7    0.4     Iris-setosa
11      5.4    3.7     1.5    0.2     Iris-setosa
15      5.8    4.0     1.2    0.2     Iris-setosa
16      5.7    4.4     1.5    0.4     Iris-setosa
..      ...    ...     ...    ...             ...
146     6.7    3.0     5.2    2.3  Iris-virginica
147     6.3    2.5     5.0    1.9  Iris-virginica
148     6.5    3.0     5.2    2.0  Iris-virginica
149     6.2    3.4     5.4    2.3  Iris-virginica
150     5.9    3.0     5.1    1.8  Iris-virginica

[118 rows x 5 columns]

### 6. Missing or bad data

Datasets, before they are "cleaned", may contain missing or wrongly formated values. There are DataFrame methods to deal with this:

- DataFrame.dropna([axis, how, thresh, …])	Remove missing values.
- DataFrame.fillna([value, method, axis, …])	Fill NA/NaN values using the specified method
- DataFrame.replace([to_replace, value, …])	Replace values given in to_replace with value.
- DataFrame.interpolate([method, axis, limit, …])	Interpolate values according to different methods.

Retrieving and cleaning data is often the most time consuming part in a data science project.

### 7. Exporting dataframes (I/O)

DataFrame has several export methods. (html, hdf5, ascii, excel etc). Let's write our file to a text file in a csv format.

In [41]:
df_large.to_csv('myout.txt')

In [42]:
%ls -l

total 16
-rw-r--r-- 1 root root 5107 Aug 22 08:43 Iris.csv
-rw-r--r-- 1 root root 4080 Aug 22 08:44 myout.txt
drwxr-xr-x 1 root root 4096 Aug 18 13:32 sample_data/

What happens with our files when we close our colab session?

### 8. Metadata


Metadata is data about the data, e.g. when was it collected, under which conditions, calibration etc.
Metadata is normally not part of the statistical data analysis, however, needed for understanding and reproducibilty.

DataFrame is not really made for storing metadata (should be done separately), but one can add new attributes to a dataframe:

In [43]:
sdf.myinstrument_name = 'Linky'
sdf.myinstrument_name

'Linky'

Data repositories often use so-called Data Cards for metadata. See for example: https://www.kaggle.com/datasets/uciml/iris

### 9. Working on the filesystem with the os module

When managing large datasets, one often has to organise files in the file system. This includes finding them, moving and copying them, creating new folders/directories, renaming them etc. This can easily be done from Python with the os (operating system) module.

Try to understand the following code and alter it to do something else.

In [44]:
import os

new_dir = os.getcwd() +'/newnbdir' # Get the current directory into a string, add /newnbdir to the string
os.makedirs(new_dir) # Create the folder
files = os.listdir() # List the files in the current folder
nb_files = [] # Create an empty list
for file in files:
    if 'ipynb' in file and file[0]!='.':
        nb_files.append(file)
for file in nb_files:
    os.system('cp '+file+' '+new_dir+'/')

In [45]:
!ls -l newnbdir

total 0

### Exercise 3 (this we may skip if not enough time)

Read in the iris dataset from iris.csv into a dataframe. Set the values in column 1 in row 39, 49 and 100 to NaN (use the nan method from the numpy package). Then replacethe NaN values to the average value of the respective column. Depending on how you do it, this may be about 10 lines of Python code.

In [46]:
# Solve your exercise here

### Exercise 4

Print a sorted list of the weeks and the male deadths with COVID-19 in Switzerland. The weeks with the highest numbers should appear first. This should be doable with about 10 lines of Python. You may need 30 minutes to solve this one.

In [47]:
import pandas as pd
#url = 'https://www.covid19.admin.ch/api/data/20210824-jrvdp23s/sources/COVID19Test_geoRegion_all.json'
#df_cov = pd.io.json.read_json(url)
#url = 'https://www.covid19.admin.ch/api/data/20210824-jrvdp23s/sources/COVID19Death_geoRegion_sex_w.csv'
url = 'https://www.covid19.admin.ch/api/data/20230815-7ixiby4u/sources/COVID19Death_geoRegion_sex_w.csv'
df_cov = pd.read_csv(url)
print(df_cov.info())
df_cov.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16188 entries, 0 to 16187
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   sex                   16188 non-null  object
 1   geoRegion             16188 non-null  object
 2   datum                 16188 non-null  int64
 3   entries               16188 non-null  int64
 4   timeframe_all         16188 non-null  bool
 5   sumTotal              16188 non-null  int64
 6   freq                  9561 non-null   float64
 7   prct                  9561 non-null   float64
 8   pop                   10792 non-null  float64
 9   inz_entries           10790 non-null  float64
 10  inzsumTotal           10790 non-null  float64
 11  type                  16188 non-null  object
 12  type_variant          16188 non-null  object
 13  version               16188 non-null  object
 14  datum_unit            16188 non-null  object
 15  datum_dboardformated  16188 non-null  object
 16  entries_diff_abs      16077 non-null  float64
 17  entries_diff_inz      10718 non-null  float64
 18  entries_diff_pct      5167 non-null   float64
 19  prct_diff             7860 non-null   float64
dtypes: bool(1), float64(9), int64(3), object(7)
memory usage: 2.4+ MB
None

,sex,geoRegion,datum,entries,timeframe_all,sumTotal,freq,prct,pop,inz_entries,inzsumTotal,type,type_variant,version,datum_unit,datum_dboardformated,entries_diff_abs,entries_diff_inz,entries_diff_pct,prct_diff
0,male,CH,202009,0,True,0,NaN,NaN,4338203.0,0.0,0.0,COVID19Death,sex,2023-08-15_06-00-29,isoweek,2020-09,NaN,NaN,NaN,NaN
1,female,CH,202009,0,True,0,NaN,NaN,4400588.0,0.0,0.0,COVID19Death,sex,2023-08-15_06-00-29,isoweek,2020-09,NaN,NaN,NaN,NaN
2,unknown,CH,202009,0,True,0,NaN,NaN,NaN,NaN,NaN,COVID19Death,sex,2023-08-15_06-00-29,isoweek,2020-09,NaN,NaN,NaN,NaN

In [48]:
g = df_cov.groupby('sex')
print(g.size())
df_mdeaths = g.get_group('male')
#df_mdeaths[50:52]
df_mdeaths_sorted = df_mdeaths.sort_values('entries',ascending=False)
df_mdeaths_sorted[['datum_dboardformated','entries']].head(20)
#df_cov['entries'].sum() # The sum is about 56k. The official number is lower, I think ... to be checked

sex
female     5396
male       5396
unknown    5396
dtype: int64

    datum_dboardformated  entries
561              2020-47      346
564              2020-48      345
117              2020-48      344
114              2020-47      343
108              2020-45      319
555              2020-45      319
573              2020-51      318
111              2020-46      317
558              2020-46      317
570              2020-50      316
123              2020-50      314
126              2020-51      312
567              2020-49      311
120              2020-49      310
576              2020-52      306
129              2020-52      301
579              2020-53      284
132              2020-53      282
582              2021-01      242
135              2021-01      239

# End of today - please fill this form

https://forms.gle/bzDpGLUieVnheZUi6.
Have a nice evening and see you tomorrow.